first commit
Edinanorge/Css_Frameworks_CA pull request #1
Opened 2023-01-25 22:15 UTC by Edinanorge

project almost done

2023-01-27 08:01 UTC, Fermain requested changes
Some minor changes here, but overall a very good looking project and varied use of SASS with bootstrap to produce an original theme.

2023-01-27 08:01 UTC, Fermain commented on home.html
> +      <div class="d-none d-lg-block mx-lg-5">
Hiding content is not a responsive strategy, please add responsive classes and/or row-col in order to accommodate  smaller screens. Mobile users deserve the same experience as desktop

2023-01-27 08:01 UTC, Fermain commented on home.html
> +          <div class="card bg-gray col-12 mx-auto">
I suggest using an extra level of div here:

```html
<div class="row feed">
  <div class="col-12">
    <div class="card bg-gray mx-auto">
```

2023-01-27 08:01 UTC, Fermain commented on profile.html
> +        <div class="container text-center m-lg-5 px-lg-5">
You shouldn't have a `.container` nested inside another `.container`.

2023-01-27 08:01 UTC, Fermain commented on profile.html
> +          <div class="d-flex flex-row add-post">
```suggestion
          <form class="d-flex flex-row add-post">
```

2023-01-27 08:01 UTC, Fermain commented on profile.html
> +      <div class="container">
Nested container again

2023-01-27 08:01 UTC, Fermain commented on profile.html
> +              <img src="/src/images/feed1.jpg" alt="" />
Empty alt tag no classes? Suggestion `.img-fluid`

2023-01-27 08:01 UTC, Fermain commented on src/scss/styles.scss
> +    margin-right: -2.7rem;
This is unusual, could you explain your choice here?

2023-01-27 08:01 UTC, Fermain commented on src/scss/styles.scss
> +.fs-6 {
By extending rather than adding to bootstrap you can achieve these results. Please see loom video for demonstration.

2023-01-27 08:12 UTC, Fermain commented
https://www.loom.com/share/f9be604237424030a8894acca6ac365a

2023-01-27 22:33 UTC, Edinanorge commented on home.html
> +          <div class="card bg-gray col-12 mx-auto">
Fixed it.

2023-01-27 22:34 UTC, Edinanorge commented on profile.html
> +          <div class="d-flex flex-row add-post">
Fixed.

2023-01-27 22:34 UTC, Edinanorge commented on profile.html
> +      <div class="container">
Corrected.

2023-01-27 22:35 UTC, Edinanorge commented on src/scss/styles.scss
> +.fs-6 {
Done. :)

2023-01-27 22:36 UTC, Edinanorge commented on profile.html
> +        <div class="container text-center m-lg-5 px-lg-5">
Fixed it.

2023-01-27 22:40 UTC, Edinanorge commented on src/scss/styles.scss
> +    margin-right: -2.7rem;
This was just a quick and dirty solution to visually put some buttons inside an input tag. But I still looking for a better way to do that. :)

2023-01-27 22:41 UTC, Edinanorge commented on profile.html
> +              <img src="/src/images/feed1.jpg" alt="" />
Fixed.

2023-01-28 12:54 UTC, Edinanorge commented on src/scss/styles.scss
> +    margin-right: -2.7rem;
Solved whit custom code - positioning.

2023-01-28 12:55 UTC, Edinanorge commented on home.html
> +      <div class="d-none d-lg-block mx-lg-5">
Fixed.

2023-03-06 09:27 UTC, merged